##  Librería de numpy

# np.where (condición)

Regresa una tupla con los indices del arreglo numpy en donde se cumple la condición.

In [1]:
import numpy as np
import random

x= np.array([2 , 6, 5, 9, 3, 9, 4, 6, 1, 8])
print(x, 'x')
np.where(x>5)




[2 6 5 9 3 9 4 6 1 8] x


(array([1, 3, 5, 7, 9], dtype=int64),)

In [5]:
np.where((x>5) & (x<9))

(array([1, 7, 9], dtype=int64),)

In [6]:
x[np.where((x>5) & (x<9))]

array([6, 6, 8])

In [7]:
x[np.where((x>5) & (x<9))]=0
print(x, 'x')

[2 0 5 9 3 9 4 0 1 0] x


# np.where (condicion, [x, y]/)

Donde la condición es verdadera, produce x, donde no produce y

In [8]:
x= np.array([2 , 6, 5, 9, 3, 9, 4, 6, 1, 8])
print(x, 'x')
np.where((x>5) & (x<9), 0, x)

[2 6 5 9 3 9 4 6 1 8] x


array([2, 0, 5, 9, 3, 9, 4, 0, 1, 0])

In [9]:
x= np.array([2 , 6, 5, 9, 3, 9, 4, 6, 1, 8])
print(x, 'x')
np.where((x>5) & (x<9), x, 0)

[2 6 5 9 3 9 4 6 1 8] x


array([0, 6, 0, 0, 0, 0, 0, 6, 0, 8])

## Se pueden comparar dos arreglos

In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a==b), type(np.where(a==b)))

(array([1, 3, 5, 7], dtype=int64),) <class 'tuple'>


In [11]:
print(b[np.where(a==b)])

[2 2 4 4]


In [12]:
b[np.where(a==b)]=10

In [13]:
print(b)

[ 7 10 10 10  7 10  9 10  9  8]


In [14]:
e=np.where(b==10, 6,b)

In [15]:
print(e)

[7 6 6 6 7 6 9 6 9 8]


In [16]:
f= np.where(b==10, b,6)
print(f)

[ 6 10 10 10  6 10  6 10  6  6]


## Numpy y máscaras 

In [17]:
x= np.array([2 , 6, 5, 9, 3, 9, 4, 6, 1, 8])
print((x>5) & (x<9))

[False  True False False False False False  True False  True]


In [18]:
x[(x>5) & (x<9)]

array([6, 6, 8])

In [19]:
x[(x>5) & (x<9)]=0
print(x, 'x')

[2 0 5 9 3 9 4 0 1 0] x


## Comparación entre arreglos bi dimensionales

In [20]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))

In [21]:
print(a,'a\n', b, 'b')

[[7 5 1]
 [2 8 2]
 [4 3 6]] a
 [[1 8 5]
 [9 4 3]
 [8 3 9]] b


In [22]:
d= a==b

In [23]:
print(d)

[[False False False]
 [False False False]
 [False  True False]]


In [24]:
type(d)

numpy.ndarray

In [25]:
a[a==b]

array([3])

In [26]:
np.where(a==b)


(array([2], dtype=int64), array([1], dtype=int64))

In [27]:
a[a<5]=0
print(a)

[[7 5 0]
 [0 8 0]
 [0 0 6]]


## np.where con arreglos bidimensionales

In [28]:
c = np.random.randint(1,10,(3,3))
d = np.random.randint(1,10,(3,3))
print(c,'c\n', d, 'd')

[[7 6 4]
 [2 1 8]
 [4 4 4]] c
 [[7 1 4]
 [8 9 2]
 [8 1 9]] d


In [29]:
np.where(c==d, c, 10)

array([[ 7, 10,  4],
       [10, 10, 10],
       [10, 10, 10]])

In [30]:
np.where(d<5, 0, 10)

array([[10,  0,  0],
       [10, 10,  0],
       [10,  0, 10]])